version: '3'

services:
  postal:
    image: crhio/postal:latest
    hostname: postal
    env_file: production.env
    volumes:
      - /data/postal:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5020:22"
